#!/usr/bin/env perl

use strict;
use warnings;

use Env;
use File::Spec;
use File::Path qw(make_path);
use File::Copy;

our $HELPER_SCRIPT;

sub setup_devops {
	my $source = File::Spec->catfile(qw(project-renard devops));
	my $target = File::Spec->catfile(qw(external project-renard devops));
	if( ! -d $target ) {
		make_path(File::Spec->catfile(qw(external project-renard)));
		move($source, $target)
	}

}

sub install {
	print "INSTALL\n";

	system(qw(perl), $HELPER_SCRIPT, qw(install));
}

sub build {
	print "BUILD\n";

	print "Nothing to build\n";
}

sub test {
	print "TEST\n";

	system(qw(perl), $HELPER_SCRIPT, qw(test));
}

sub main {
	setup_devops;

	$ENV{COMPILER} = "msys2";
	$ENV{PLATFORM} = "x64";
	$ENV{MSYS2_ARCH} = "x86_64";
	$ENV{MSYS2_DIR} = "msys64";
	$ENV{MSYSTEM} = "MINGW64";
	$ENV{BIT} = 64;

	## running under CI
	$ENV{CI_TESTING} = 1;
	$ENV{DEVOPS_BRANCH} = "master";

	$HELPER_SCRIPT = File::Spec->rel2abs(
		File::Spec->catfile(
			qw(external project-renard devops script helper.pl)
		)
	);

	$ENV{APPVEYOR_BUILD_FOLDER} = File::Spec->catfile($ENV{APPVEYOR_BUILD_FOLDER}, "curie");

	if( ! -d $ENV{APPVEYOR_BUILD_FOLDER} ) {
		system(qw(git clone https://github.com/project-renard/curie.git), $ENV{APPVEYOR_BUILD_FOLDER});
	}
	chdir $ENV{APPVEYOR_BUILD_FOLDER};

	my %function_lookup = (
		install => \&install,
		build   => \&build,
		test    => \&test,
	);

	if( exists $ARGV[0] && exists $function_lookup{$ARGV[0]} ) {
		$function_lookup{$ARGV[0]}->();
	}
}

main;
