#!/bin/sh

if [ "$TRAVIS_OS_NAME" = "linux" ]; then
	$ORBITAL_LAUNCH_SITE_DIR/maint/build-docker
	docker ps -a
elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
	brew update
	export HOMEBREW_NO_AUTO_UPDATE=1
	brew install perl
	$ORBITAL_LAUNCH_SITE_DIR/maint/replace-shebang $ORBITAL_LAUNCH_SITE_DIR/vendor/p5-Orbital-Launch/bin/orbitalism

	orbitalism bootstrap auto
fi
