#!/bin/sh

if [ "$TRAVIS_OS_NAME" = "linux" ]; then
	$OBERTH_PROTOTYPE_DIR/maint/build-docker
	docker ps -a
elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
	brew update
	export HOMEBREW_NO_AUTO_UPDATE=1
	brew install perl
	$OBERTH_PROTOTYPE_DIR/maint/replace-shebang $OBERTH_PROTOTYPE_DIR/vendor/p5-Oberth-Launch/bin/oberthian

	oberthian bootstrap auto
fi
