#!/bin/bash

if [ "$TRAVIS_OS_NAME" = "linux" ]; then
	docker run --rm -it \
		$(perl -e 'print join " ", map { "-e $_" } grep { /^OBERTH_/ } keys %ENV') \
		--mount type=bind,source=$OBERTH_TEST_DIR,target=/build/repository \
		oberth:latest
elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
	cd $OBERTH_TEST_DIR && oberthian
	cd $OBERTH_TEST_DIR && oberthian test
fi
