#!/bin/bash

if [ "$TRAVIS_OS_NAME" = "linux" ]; then
	docker run --rm -it \
		$(perl -e 'print join " ", map { "-e $_" } grep { /^ORBITAL_/ } keys %ENV') \
		$(perl -e 'print join " ", map { "-e $_" } grep { /^TRAVIS/ } keys %ENV') \
		-e "ORBITAL_TEST_DIR=/build/repository" \
		--mount type=bind,source=$ORBITAL_TEST_DIR,target=/build/repository \
		orbital:latest
elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
	cd $ORBITAL_TEST_DIR && orbitalism
	cd $ORBITAL_TEST_DIR && orbitalism test
fi
