#!/bin/sh

CURDIR=`dirname "$0"`
cd $CURDIR/..

DEFAULT_RUN="perl -I/build/curie/local/lib/perl5 -Mlocal::lib=/build/curie/local /build/curie/bin/curie"

if [ -z "$@" ]; then
	RUN=$DEFAULT_RUN
else
	RUN=$@
fi

if [ -r /home/zaki/sw_projects ]; then
MY_MOUNT_VOLUMES="
	--mount type=bind,source=/home/zaki/sw_projects/project-renard,target=/project-renard
	--mount type=bind,source=/home/zaki/sw_projects/oberth-manoeuvre,target=/oberth-manoeuvre
"
else
MY_MOUNT_VOLUMES=""
fi


xhost +local:root

docker run --rm -it \
	--env="DISPLAY" \
	--volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
	$MY_MOUNT_VOLUMES \
	oberth:latest \
	$RUN


xhost -local:root
