#!/bin/sh

CURDIR=`dirname "$0"`
cd $CURDIR/..

PDF_REFERENCE_PATH="/build/external/project-renard/test-data/PDF/Adobe/pdf_reference_1-7.pdf"
DEFAULT_RUN="perl -I/build/repository/local/lib/perl5 -Mlocal::lib=/build/repository/local /build/repository/bin/curie $PDF_REFERENCE_PATH"

if [ -z "$@" ]; then
	RUN=$DEFAULT_RUN
else
	RUN=$@
fi

if [ -r /home/zaki/sw_projects ]; then
MY_MOUNT_VOLUMES="
	--mount type=bind,source=/home/zaki/sw_projects/project-renard,target=/project-renard
	--mount type=bind,source=/home/zaki/sw_projects/orbital-transfer,target=/orbital-transfer
"
else
MY_MOUNT_VOLUMES=""
fi


xhost +si:localuser:root

docker run --rm -it \
	--env="DISPLAY" \
	--volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
	$MY_MOUNT_VOLUMES \
	orbital:latest \
	$RUN


xhost -si:localuser:root
